# Generated by Django 4.1.6 on 2023-03-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SinglePage', '0002_remove_user_walletid_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='MoneySpent',
            field=models.FloatField(default=0),
        ),
    ]
